# Generated by Django 5.0.6 on 2024-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="abilities",
            field=models.CharField(),
        ),
    ]
